// TEMPORARY DATA

export let role = "admin";

export const employeesData = [
  {
    "ID": "EMP0001",
    "Nama": "Warta Pradipta",
    "Tim": "C",
    "Status Karyawan": "contract",
    "Tanggal Masuk": "2027-08-12",
    "Tanggal Lahir": "2001-01-15",
    "Line Asal": "Line 3",
    "Alamat": "Jl. S. Parman No. 46, Pagaralam, PB 68232",
    "No. Telepon": "+62 (42) 674-3785",
    "Email": "fitriani57@example.org",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Diploma",
    "Posisi": "Manajer",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/women/51.jpg"
  },
  {
    "ID": "EMP0002",
    "Nama": "Lidya Hakim",
    "Tim": "A",
    "Status Karyawan": "permanent",
    "Tanggal Masuk": "2028-05-25",
    "Tanggal Lahir": "2002-06-01",
    "Line Asal": "Line 4",
    "Alamat": "Gg. S. Parman No. 68, Lubuklinggau, JB 33036",
    "No. Telepon": "(027) 879-0735",
    "Email": "jarwasantoso@example.org",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Sarjana",
    "Posisi": "Supervisor",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/86.jpg"
  },
  {
    "ID": "EMP0003",
    "Nama": "R.A. Belinda Saptono",
    "Tim": "A",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2012-12-20",
    "Tanggal Lahir": "1980-05-07",
    "Line Asal": "Line 1",
    "Alamat": "Jalan Jend. Sudirman No. 22, Pekalongan, Jawa Tengah 59467",
    "No. Telepon": "+62-44-867-6515",
    "Email": "mpranowo@example.org",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Magister",
    "Posisi": "Operator",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/women/50.jpg"
  },
  {
    "ID": "EMP0004",
    "Nama": "Cawuk Simanjuntak",
    "Tim": "A",
    "Status Karyawan": "permanent",
    "Tanggal Masuk": "2013-06-02",
    "Tanggal Lahir": "1986-01-17",
    "Line Asal": "Line 2",
    "Alamat": "Gang Ciumbuleuit No. 931, Bogor, Sulawesi Selatan 73511",
    "No. Telepon": "+62-0614-325-8174",
    "Email": "estiono30@example.com",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Diploma",
    "Posisi": "Supervisor",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/95.jpg"
  },
  {
    "ID": "EMP0005",
    "Nama": "Samiah Putra",
    "Tim": "B",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2024-08-09",
    "Tanggal Lahir": "2000-08-31",
    "Line Asal": "Line 3",
    "Alamat": "Gang Rawamangun No. 748, Semarang, ST 83862",
    "No. Telepon": "+62-411-370-8466",
    "Email": "bahuraksakusmawati@example.com",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "SMA",
    "Posisi": "Operator",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/men/9.jpg"
  },
  {
    "ID": "EMP0006",
    "Nama": "Galur Hassanah",
    "Tim": "C",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2024-02-20",
    "Tanggal Lahir": "1998-10-13",
    "Line Asal": "Line 4",
    "Alamat": "Gg. Kapten Muslihat No. 5, Makassar, Jambi 26848",
    "No. Telepon": "(040) 852 5069",
    "Email": "salsabilafarida@example.net",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Diploma",
    "Posisi": "Manajer",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/women/76.jpg"
  },
  {
    "ID": "EMP0007",
    "Nama": "Karen Sirait",
    "Tim": "A",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2010-02-14",
    "Tanggal Lahir": "1981-04-20",
    "Line Asal": "Line 1",
    "Alamat": "Jalan Kiaracondong No. 074, Banjar, Papua Barat 19754",
    "No. Telepon": "+62 (77) 790-9890",
    "Email": "luweswidiastuti@example.com",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "SMA",
    "Posisi": "Supervisor",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/women/79.jpg"
  },
  {
    "ID": "EMP0008",
    "Nama": "Puput Gunarto",
    "Tim": "B",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2007-01-18",
    "Tanggal Lahir": "1984-07-20",
    "Line Asal": "Line 1",
    "Alamat": "Gang Kendalsari No. 60, Kediri, MU 02396",
    "No. Telepon": "+62 (97) 003 3322",
    "Email": "adriansyahyosef@example.net",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Magister",
    "Posisi": "Supervisor",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/7.jpg"
  },
  {
    "ID": "EMP0009",
    "Nama": "Aris Situmorang",
    "Tim": "A",
    "Status Karyawan": "contract",
    "Tanggal Masuk": "2018-12-27",
    "Tanggal Lahir": "1992-12-05",
    "Line Asal": "Line 3",
    "Alamat": "Gang Asia Afrika No. 6, Lubuklinggau, Aceh 09455",
    "No. Telepon": "+62-392-238-2209",
    "Email": "okta56@example.net",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Diploma",
    "Posisi": "Manajer",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/women/70.jpg"
  },
  {
    "ID": "EMP0010",
    "Nama": "Dt. Hardana Rajata, M.TI.",
    "Tim": "A",
    "Status Karyawan": "contract",
    "Tanggal Masuk": "2006-06-08",
    "Tanggal Lahir": "1982-01-29",
    "Line Asal": "Line 1",
    "Alamat": "Gang Cikapayang No. 98, Salatiga, Banten 24628",
    "No. Telepon": "+62-0192-359-9247",
    "Email": "musada@example.org",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Sarjana",
    "Posisi": "Supervisor",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/men/8.jpg"
  },
  {
    "ID": "EMP0011",
    "Nama": "Harja Zulaika",
    "Tim": "A",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2011-10-10",
    "Tanggal Lahir": "1983-07-25",
    "Line Asal": "Line 4",
    "Alamat": "Gg. Merdeka No. 2, Padang, Kalimantan Utara 72011",
    "No. Telepon": "+62 (0635) 155-1856",
    "Email": "fitrianimansur@example.org",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Sarjana",
    "Posisi": "Teknisi",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/women/40.jpg"
  },
  {
    "ID": "EMP0012",
    "Nama": "Prabowo Mayasari",
    "Tim": "A",
    "Status Karyawan": "contract",
    "Tanggal Masuk": "2001-10-08",
    "Tanggal Lahir": "1972-10-02",
    "Line Asal": "Line 4",
    "Alamat": "Gg. M.T Haryono No. 2, Kendari, Nusa Tenggara Barat 54519",
    "No. Telepon": "+62 (08) 796 8452",
    "Email": "permataagnes@example.net",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Diploma",
    "Posisi": "Manajer",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/women/46.jpg"
  },
  {
    "ID": "EMP0013",
    "Nama": "Oliva Maryati, S.Gz",
    "Tim": "B",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2029-03-25",
    "Tanggal Lahir": "2001-11-02",
    "Line Asal": "Line 3",
    "Alamat": "Jalan Rawamangun No. 88, Subulussalam, SS 23065",
    "No. Telepon": "0811313918",
    "Email": "latikalestari@example.org",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "SMA",
    "Posisi": "Manajer",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/women/5.jpg"
  },
  {
    "ID": "EMP0014",
    "Nama": "Wirda Irawan",
    "Tim": "C",
    "Status Karyawan": "contract",
    "Tanggal Masuk": "2026-04-04",
    "Tanggal Lahir": "2000-07-18",
    "Line Asal": "Line 4",
    "Alamat": "Jl. Sukabumi No. 677, Tebingtinggi, Kalimantan Selatan 90728",
    "No. Telepon": "085 265 7258",
    "Email": "rahmi51@example.org",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "SMA",
    "Posisi": "Supervisor",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/women/75.jpg"
  },
  {
    "ID": "EMP0015",
    "Nama": "Jessica Sihotang",
    "Tim": "B",
    "Status Karyawan": "permanent",
    "Tanggal Masuk": "2007-10-22",
    "Tanggal Lahir": "1980-12-07",
    "Line Asal": "Line 3",
    "Alamat": "Gang Antapani Lama No. 0, Tangerang, JK 82011",
    "No. Telepon": "0891436255",
    "Email": "daryani13@example.org",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "SMA",
    "Posisi": "Teknisi",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/75.jpg"
  },
  {
    "ID": "EMP0016",
    "Nama": "Rafid Andriani, S.T.",
    "Tim": "C",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2022-01-04",
    "Tanggal Lahir": "1989-12-09",
    "Line Asal": "Line 4",
    "Alamat": "Jalan H.J Maemunah No. 71, Tangerang Selatan, LA 76502",
    "No. Telepon": "+62 (068) 469-3733",
    "Email": "estiawandabukke@example.org",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Sarjana",
    "Posisi": "Supervisor",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/women/1.jpg"
  },
  {
    "ID": "EMP0017",
    "Nama": "Dt. Saiful Handayani, S.Pd",
    "Tim": "B",
    "Status Karyawan": "contract",
    "Tanggal Masuk": "2011-10-04",
    "Tanggal Lahir": "1979-05-08",
    "Line Asal": "Line 3",
    "Alamat": "Jl. Cikapayang No. 28, Tangerang Selatan, AC 20928",
    "No. Telepon": "+62 (092) 072 2321",
    "Email": "corneliamayasari@example.org",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "SMA",
    "Posisi": "Operator",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/women/32.jpg"
  },
  {
    "ID": "EMP0018",
    "Nama": "Oliva Lailasari",
    "Tim": "B",
    "Status Karyawan": "contract",
    "Tanggal Masuk": "2019-02-14",
    "Tanggal Lahir": "1992-12-02",
    "Line Asal": "Line 3",
    "Alamat": "Jl. R.E Martadinata No. 0, Singkawang, BA 53905",
    "No. Telepon": "+62-27-367-6773",
    "Email": "rahimahajeng@example.net",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Diploma",
    "Posisi": "Teknisi",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/men/31.jpg"
  },
  {
    "ID": "EMP0019",
    "Nama": "Malika Riyanti",
    "Tim": "C",
    "Status Karyawan": "contract",
    "Tanggal Masuk": "2006-08-10",
    "Tanggal Lahir": "1975-01-04",
    "Line Asal": "Line 4",
    "Alamat": "Jalan Rajiman No. 10, Bitung, Sulawesi Selatan 89534",
    "No. Telepon": "+62 (638) 881 2030",
    "Email": "hartaka54@example.org",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "SMA",
    "Posisi": "Operator",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/8.jpg"
  },
  {
    "ID": "EMP0020",
    "Nama": "Hari Manullang",
    "Tim": "C",
    "Status Karyawan": "contract",
    "Tanggal Masuk": "1994-09-06",
    "Tanggal Lahir": "1972-01-04",
    "Line Asal": "Line 1",
    "Alamat": "Gg. Cempaka No. 521, Sibolga, Kalimantan Tengah 93490",
    "No. Telepon": "+62 (56) 482-4142",
    "Email": "ilyaspuspita@example.net",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Magister",
    "Posisi": "Operator",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/19.jpg"
  },
  {
    "ID": "EMP0021",
    "Nama": "Salimah Anggraini, S.Farm",
    "Tim": "C",
    "Status Karyawan": "permanent",
    "Tanggal Masuk": "2020-11-22",
    "Tanggal Lahir": "1989-05-11",
    "Line Asal": "Line 3",
    "Alamat": "Jalan Cikutra Timur No. 146, Tidore Kepulauan, Sulawesi Tenggara 05157",
    "No. Telepon": "+62-70-956-1654",
    "Email": "ajanuar@example.com",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Magister",
    "Posisi": "Supervisor",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/36.jpg"
  },
  {
    "ID": "EMP0022",
    "Nama": "Dr. Hani Padmasari",
    "Tim": "A",
    "Status Karyawan": "permanent",
    "Tanggal Masuk": "2006-04-07",
    "Tanggal Lahir": "1976-11-03",
    "Line Asal": "Line 1",
    "Alamat": "Gg. HOS. Cokroaminoto No. 0, Palangkaraya, NB 94029",
    "No. Telepon": "+62-041-063-5859",
    "Email": "rhariyah@example.com",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Magister",
    "Posisi": "Teknisi",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/men/30.jpg"
  },
  {
    "ID": "EMP0023",
    "Nama": "Siti Sihombing",
    "Tim": "C",
    "Status Karyawan": "permanent",
    "Tanggal Masuk": "1991-09-03",
    "Tanggal Lahir": "1971-05-19",
    "Line Asal": "Line 4",
    "Alamat": "Jalan Medokan Ayu No. 722, Salatiga, JI 96090",
    "No. Telepon": "(087) 786 6521",
    "Email": "gkusumo@example.com",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Magister",
    "Posisi": "Teknisi",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/women/49.jpg"
  },
  {
    "ID": "EMP0024",
    "Nama": "Prakosa Suryono",
    "Tim": "A",
    "Status Karyawan": "permanent",
    "Tanggal Masuk": "1998-10-17",
    "Tanggal Lahir": "1978-08-02",
    "Line Asal": "Line 2",
    "Alamat": "Jl. Dipatiukur No. 562, Subulussalam, JB 08708",
    "No. Telepon": "+62-002-550-3391",
    "Email": "ajimin61@example.com",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Magister",
    "Posisi": "Operator",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/44.jpg"
  },
  {
    "ID": "EMP0025",
    "Nama": "Asmianto Usamah",
    "Tim": "A",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2033-10-09",
    "Tanggal Lahir": "2004-01-21",
    "Line Asal": "Line 3",
    "Alamat": "Jl. Siliwangi No. 999, Manado, Sumatera Selatan 11716",
    "No. Telepon": "+62 (435) 114-9987",
    "Email": "vinosuartini@example.com",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Sarjana",
    "Posisi": "Operator",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/61.jpg"
  },
  {
    "ID": "EMP0026",
    "Nama": "R. Jatmiko Mangunsong, M.Pd",
    "Tim": "A",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2002-11-17",
    "Tanggal Lahir": "1977-07-18",
    "Line Asal": "Line 4",
    "Alamat": "Gg. Rungkut Industri No. 651, Tarakan, LA 76567",
    "No. Telepon": "+62 (74) 451-1413",
    "Email": "cemetifujiati@example.org",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Sarjana",
    "Posisi": "Teknisi",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/women/66.jpg"
  },
  {
    "ID": "EMP0027",
    "Nama": "Maida Oktaviani",
    "Tim": "A",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2010-11-13",
    "Tanggal Lahir": "1986-04-19",
    "Line Asal": "Line 4",
    "Alamat": "Jalan Kiaracondong No. 3, Pasuruan, Nusa Tenggara Timur 09598",
    "No. Telepon": "(019) 390 2214",
    "Email": "dwibisono@example.net",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "Sarjana",
    "Posisi": "Teknisi",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/women/17.jpg"
  },
  {
    "ID": "EMP0028",
    "Nama": "Dr. Chelsea Yuniar, S.Ked",
    "Tim": "C",
    "Status Karyawan": "permanent",
    "Tanggal Masuk": "2020-09-06",
    "Tanggal Lahir": "1996-12-11",
    "Line Asal": "Line 1",
    "Alamat": "Gg. Cikutra Timur No. 46, Surakarta, Papua Barat 70539",
    "No. Telepon": "+62 (381) 336 9260",
    "Email": "mansurkurnia@example.com",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "Diploma",
    "Posisi": "Teknisi",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/women/74.jpg"
  },
  {
    "ID": "EMP0029",
    "Nama": "Zulaikha Latupono",
    "Tim": "B",
    "Status Karyawan": "third party",
    "Tanggal Masuk": "2026-07-19",
    "Tanggal Lahir": "2001-02-08",
    "Line Asal": "Line 3",
    "Alamat": "Jalan Moch. Ramdan No. 2, Jayapura, Kalimantan Barat 59574",
    "No. Telepon": "+62-638-385-2775",
    "Email": "hpratiwi@example.org",
    "Jenis Kelamin": "Laki-laki",
    "Pendidikan": "SMA",
    "Posisi": "Operator",
    "Status Aktif": true,
    "Foto": "https://randomuser.me/api/portraits/men/65.jpg"
  },
  {
    "ID": "EMP0030",
    "Nama": "Bahuwirya Hidayat",
    "Tim": "A",
    "Status Karyawan": "permanent",
    "Tanggal Masuk": "2011-05-14",
    "Tanggal Lahir": "1986-04-15",
    "Line Asal": "Line 1",
    "Alamat": "Gg. Rajawali Barat No. 5, Purwokerto, KR 66547",
    "No. Telepon": "+62 (0489) 009 1754",
    "Email": "purwantiharsanto@example.com",
    "Jenis Kelamin": "Perempuan",
    "Pendidikan": "SMA",
    "Posisi": "Operator",
    "Status Aktif": false,
    "Foto": "https://randomuser.me/api/portraits/women/59.jpg"
  }
];

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];